<a href="https://colab.research.google.com/github/Asfiashub/Mini-Projects/blob/main/Academic/MCET_LAB_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **22-AUG-2026**

---



## PROGRAM 1


In [ ]:
import tensorflow as tf

# Ensure TensorFlow version 2.x is used
print(f"Using TensorFlow version: {tf.__version__}\n")

# =====================================================================
# 1. TENSOR CREATION
# =====================================================================
print("--- 1. Tensor Creation ---")

# Creating a 1D tensor (Vector) from a Python list
tensor_1d = tf.constant([1.0, 2.0, 3.0, 4.0], dtype=tf.float32)

# Creating a 2D tensor (Matrix)
tensor_2d = tf.constant([[1, 2], [3, 4]], dtype=tf.int32)

# Creating tensors filled with constants or random values
tensor_zeros = tf.zeros(shape=(2, 3))  # 2x3 matrix of zeros
tensor_ones = tf.ones(shape=(2, 3))   # 2x3 matrix of ones

# Random tensors (crucial for initializing weights in neural networks)
tensor_random_norm = tf.random.normal(shape=(2, 2), mean=0.0, stddev=1.0)
tensor_random_uni = tf.random.uniform(shape=(2, 2), minval=0, maxval=10)

print("2D Constant Tensor:\n", tensor_2d)
print("Random Normal Tensor:\n", tensor_random_norm)


Using TensorFlow version: 2.20.0

--- 1. Tensor Creation ---
2D Constant Tensor:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Random Normal Tensor:
 tf.Tensor(
[[-0.08634774 -0.4295143 ]
 [ 0.26919726  1.8884535 ]], shape=(2, 2), dtype=float32)


In [ ]:

# =====================================================================
# 2. MATHEMATICAL OPERATIONS
# =====================================================================
print("\n--- 2. Mathematical Operations ---")

a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Element-wise operations (shapes must match or be broadcastable)
element_add = tf.add(a, b)         # Or simply: a + b
element_mul = tf.multiply(a, b)    # Or simply: a * b (NOT matrix multiplication)

# Matrix Multiplication (Dot Product) - Essential for Deep Learning
# Condition: Columns of 'a' must equal Rows of 'b'
matrix_mul = tf.matmul(a, b)       # Or simply: a @ b

# Exponential and Square Root
tensor_exp = tf.exp(a)
tensor_sqrt = tf.sqrt(a)

print("Element-wise Multiplication (a * b):\n", element_mul.numpy())
print("Matrix Multiplication (a @ b):\n", matrix_mul.numpy())




--- 2. Mathematical Operations ---
Element-wise Multiplication (a * b):
 [[ 5. 12.]
 [21. 32.]]
Matrix Multiplication (a @ b):
 [[19. 22.]
 [43. 50.]]


In [ ]:


# =====================================================================
# 3. STATISTICAL OPERATIONS
# =====================================================================
print("\n--- 3. Statistical Operations ---")

c = tf.constant([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0]], dtype=tf.float32)

# Global statistics (reduces the entire tensor to a single scalar value)
global_sum = tf.reduce_sum(c)
global_mean = tf.reduce_mean(c)

# Axis-specific statistics (reducing across rows or columns)
# axis=0 represents rows (collapses vertically to find stat for each column)
mean_across_rows = tf.reduce_mean(c, axis=0)

# axis=1 represents columns (collapses horizontally to find stat for each row)
max_across_columns = tf.reduce_max(c, axis=1)

# Finding indices of min/max values (useful for classification outputs)
# argmax returns the index of the highest value
argmax_indices = tf.argmax(c, axis=1)

print("Global Mean:", global_mean.numpy())
print("Mean across rows (axis=0):", mean_across_rows.numpy())
print("Argmax across columns (axis=1):", argmax_indices.numpy())




--- 3. Statistical Operations ---
Global Mean: 3.5
Mean across rows (axis=0): [2.5 3.5 4.5]
Argmax across columns (axis=1): [2 2]


In [ ]:

# =====================================================================
# 4. RESHAPING AND MANIPULATION
# =====================================================================
print("\n--- 4. Reshaping & Manipulation ---")

d = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32) # Shape (2, 3)

# Reshaping a tensor (Total elements must remain identical: 2 * 3 = 6)
# Using -1 tells TensorFlow to automatically compute that specific dimension
reshaped_d = tf.reshape(d, shape=(3, 2))
flattened_d = tf.reshape(d, shape=(-1,)) # Flattens to a 1D vector of shape (6,)

# Transposing a matrix (swapping rows and columns)
transposed_d = tf.transpose(d) # Shape becomes (3, 2)

# Adding and removing dimensions (Squeezing and Expanding)
# Expand dims adds a dimension of size 1 at the specified axis
expanded_d = tf.expand_dims(d, axis=0) # Shape becomes (1, 2, 3)

# Squeeze removes dimensions of size 1
squeezed_d = tf.squeeze(expanded_d, axis=0) # Shape goes back to (2, 3)

print("Original Shape:", d.shape)
print("Reshaped to (3, 2):\n", reshaped_d.numpy())
print("Flattened Vector:", flattened_d.numpy())
print("Expanded Shape (axis=0):", expanded_d.shape)



--- 4. Reshaping & Manipulation ---
Original Shape: (2, 3)
Reshaped to (3, 2):
 [[1 2]
 [3 4]
 [5 6]]
Flattened Vector: [1 2 3 4 5 6]
Expanded Shape (axis=0): (1, 2, 3)


## PROGRAM 2

In [ ]:
import tensorflow as tf

# Ensure TensorFlow version 2.x is used
print(f"Using TensorFlow version: {tf.__version__}\n")

# =====================================================================
# 1. TENSOR CREATION
# =====================================================================
print("--- 1. Tensor Creation ---")
# Creating base tensors to demonstrate split, merge, and stats
matrix_a = tf.constant([[1.0, 2.0, 3.0],
                        [4.0, 5.0, 6.0]], dtype=tf.float32) # Shape: (2, 3)

matrix_b = tf.constant([[7.0, 8.0, 9.0],
                        [10.0, 11.0, 12.0]], dtype=tf.float32) # Shape: (2, 3)

print("Matrix A:\n", matrix_a.numpy())
print("Matrix B:\n", matrix_b.numpy())




Using TensorFlow version: 2.20.0

--- 1. Tensor Creation ---
Matrix A:
 [[1. 2. 3.]
 [4. 5. 6.]]
Matrix B:
 [[ 7.  8.  9.]
 [10. 11. 12.]]


In [ ]:
# =====================================================================
# 2. MERGE OPERATIONS (CONCATENATE VS. STACK)
# =====================================================================
print("\n--- 2. Merge Operations ---")

# tf.concat: Joins existing tensors along an EXISTING dimension.
# The shapes must match exactly except along the target axis.
concat_axis0 = tf.concat([matrix_a, matrix_b], axis=0) # Combines vertically -> Shape: (4, 3)
concat_axis1 = tf.concat([matrix_a, matrix_b], axis=1) # Combines horizontally -> Shape: (2, 6)

print("Concatenated along axis 0 (Vertical):\n", concat_axis0.numpy())
print("Concatenated along axis 1 (Horizontal):\n", concat_axis1.numpy())

# tf.stack: Joins tensors along a BRAND NEW dimension (creates a higher-rank tensor).
# Tensors being stacked must have identical shapes.
stacked_axis0 = tf.stack([matrix_a, matrix_b], axis=0) # Shape: (2, 2, 3) - e.g., a batch of 2 matrices

print("\nStacked along a new axis 0 (Batch dimension added):\n", stacked_axis0.numpy())
print("Stacked Shape:", stacked_axis0.shape)




--- 2. Merge Operations ---
Concatenated along axis 0 (Vertical):
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Concatenated along axis 1 (Horizontal):
 [[ 1.  2.  3.  7.  8.  9.]
 [ 4.  5.  6. 10. 11. 12.]]

Stacked along a new axis 0 (Batch dimension added):
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
Stacked Shape: (2, 2, 3)


In [ ]:

# =====================================================================
# 3. SPLIT OPERATIONS
# =====================================================================
print("\n--- 3. Split Operations ---")

# tf.split: Cuts a tensor into multiple sub-tensors along a specified axis.
# Scenario A: Splitting into equal sized pieces. Pass an integer count.
# Splitting concat_axis0 (4, 3) back into 2 equal parts along axis 0
split_equal = tf.split(concat_axis0, num_or_size_splits=2, axis=0)

# Scenario B: Splitting into unequal chunks. Pass a list of sizes.
# Splitting concat_axis1 (2, 6) into chunks of sizes 1, 2, and 3 along axis 1
split_unequal = tf.split(concat_axis1, num_or_size_splits=[1, 2, 3], axis=1)

print("Equal Split Part 1:\n", split_equal[0].numpy())
print("Unequal Split Part 2 (Expected width of 2):\n", split_unequal[1].numpy())



--- 3. Split Operations ---
Equal Split Part 1:
 [[1. 2. 3.]
 [4. 5. 6.]]
Unequal Split Part 2 (Expected width of 2):
 [[2. 3.]
 [5. 6.]]


In [ ]:


# =====================================================================
# 4. STATISTICAL OPERATIONS
# =====================================================================
print("\n--- 4. Statistical Operations ---")

# Let's use a fresh tensor with varied values for clear statistical variance
stat_tensor = tf.constant([[1.0, 5.0, 9.0],
                           [2.0, 4.0, 12.0]], dtype=tf.float32)

# Variance and Standard Deviation
# Note: TensorFlow requires the input to be float32 or float64 for moments
variance = tf.math.reduce_variance(stat_tensor)
std_dev = tf.math.reduce_std(stat_tensor, axis=0) # calculated across rows per column

# Top-K Elements: Finds the 'K' largest values and their indices along the last axis
# Very useful for evaluating top-3 accuracy in multi-class classification
top_k_values, top_k_indices = tf.math.top_k(stat_tensor, k=2)

# Cumulative Sum & Cumulative Product
cumsum_axis1 = tf.math.cumsum(stat_tensor, axis=1)

print("Global Variance:", variance.numpy())
print("Standard Deviation across rows (axis=0):", std_dev.numpy())
print("Top 2 values in each row:\n", top_k_values.numpy())
print("Top 2 value indices in each row:\n", top_k_indices.numpy())
print("Cumulative sum across columns (axis=1):\n", cumsum_axis1.numpy())



--- 4. Statistical Operations ---
Global Variance: 14.916667
Standard Deviation across rows (axis=0): [0.5 0.5 1.5]
Top 2 values in each row:
 [[ 9.  5.]
 [12.  4.]]
Top 2 value indices in each row:
 [[2 1]
 [2 1]]
Cumulative sum across columns (axis=1):
 [[ 1.  6. 15.]
 [ 2.  6. 18.]]


## **29-Aug-2026**

## PROGRAM-3

In [ ]:
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

#load iris datasets
iris = load_iris()
# first 100 samples, first 2 features{ sepal length, sepal width}
